services:
  consumer:
    container_name: "consumer"
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8001:8000
    volumes:
      - .:/app/api/go-app
    networks:
      - go_api_network

networks:
  go_api_network:
    driver: bridge
    external: true
